[general]
# Log level
#
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=4
# server port
port=8888
# server mode
# options:debug, release
mode="release"
# upload file path.
# if exists upload file in the path,don't change it.
uploadpath="./uploadfile/"

[mysql]
# data source name
dsn="root:blog@tcp(localhost:3306)/blog?parseTime=true"
#
auto_migrate=true 

# blog configuration
[blogconf]
    [blogconf.data]
    globaltitle = "阿汤哥的博客"
    globalkeyword = "博客,记录生活"
    globaldesp = "记录生活的点点滴滴"
    pageoffset=9